### ISSUE TITLE
sqlite3.OperationalError: no such table: startwords

### ISSUE THREAD

**Issue by Euphorbium** [kspi/delfi-journalist#1]
When I run generate.py (after generating the db), I get the following:

```
Traceback (most recent call last):
  File "generate.py", line 36, in <module>
    main()
  File "generate.py", line 33, in main
    print(generate_title(db))
  File "generate.py", line 25, in generate_title
    ws = generate_title_words(db)
  File "generate.py", line 9, in generate_title_words
    c.execute('SELECT word, frequency FROM startwords;')
sqlite3.OperationalError: no such table: startwords
```

**Comment by kspi** [comment]
generate.py is an earlier version of the generator left for reference and the schema has since changed. I might fix it later. For now you should launch compact.py, make and then ./generate .
